service: ${env:APP_NAME}
frameworkVersion: '3'

useDotenv: true

configValidationMode: warn

deprecationNotificationMode: warn:summary

provider:
  name: aws
  stage: ${env:STAGE, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  region: ${env:AWS_REGION, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter*
          Resource:
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:provider.stage}/${self:service}
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:provider.stage}/${self:service}/*
  environment:
    APP_NAME: ${self:service}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    STAGE: ${self:provider.stage}
    ALLOW_CORS_ORIGIN: ${env:ALLOW_CORS_ORIGIN, '${ssm:/${self:provider.stage}/${self:service}/ALLOW_CORS_ORIGIN}'}

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager
  - serverless-frontend-plugin
  - serverless-offline

custom:
  httpPort: ${env:HTTP_PORT, 3000}
  serverless-offline:
    httpPort: ${self:custom.httpPort}
  # API Domain Configuration
  customDomain:
    domainName: ${env:API_DOMAIN_NAME}
    stage: ${self:provider.stage}
    basePath: ''
    certificateArn: ${env:AWS_ACM_CERTIFICATE_ARN}
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true
  # Frontend Configuration
  serverless-frontend-plugin:
    distDir: frontend/dist
    build:
      cwdDir: frontend
      command:
        - npm
        - run
        - build
      env:
        VUE_APP_API_BASE_URL: https://${env:API_DOMAIN_NAME}
    distribution:
      acmCertificateArn: ${env:AWS_ACM_CERTIFICATE_ARN}
      dnsName: ${env:FRONTEND_DOMAIN_NAME}
      hostedZoneName: ${env:HOSTED_ZONE_NAME}
    offline:
      env:
        VUE_APP_API_BASE_URL: http://localhost:${self:custom.httpPort}
      command:
        - npm
        - run
        - serve

functions:
  api:
    handler: src/index.api
    events:
      - httpApi: '*'
